server:
  port: 8080
  
logging:
  level:
    root: DEBUG

spring:
  application:
    name: API-GATEWAY

  config:
    import: optional:configserver:http://localhost:8888

  cloud:
    gateway:
      routes:
        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/product/**
          filters:
            - StripPrefix=1
          

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
